version: '3.8'

services:
  dataBase:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=apimusic
      - POSTGRES_DB=apimusic
    ports:
      - 3369:5432
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d        

  app:
    build: . 
    links:
      - dataBase
    ports:
      - 3000:3000  # Ajusta el puerto según las necesidades de tu aplicación
                       