CREATE TABLE artist (
    id INT PRIMARY KEY,
    nombre VARCHAR(255),
    generomusica VARCHAR(100),
    nacimiento DATE,
    paisorigen VARCHAR(100)
);

insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (149, 'ycornforth0', 'Action|Drama|Fantasy', '2023-07-17', 'Italy');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (167, 'spollastro1', 'Comedy|Drama|Musical|Romance', '2023-06-17', 'Honduras');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (58, 'aguppy2', 'Horror', '2023-05-30', 'Tanzania');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (72, 'cedmands3', 'Comedy', '2023-02-04', 'China');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (173, 'jbailes4', 'Comedy|Drama|Romance', '2022-12-18', 'Russia');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (144, 'ggeorgelin5', 'Drama', '2023-10-16', 'Brazil');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (56, 'cstellino6', 'Drama', '2023-11-14', 'Madagascar');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (22, 'nnewlove7', 'Comedy|Drama|Romance', '2023-05-07', 'Indonesia');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (94, 'rgepheart8', 'Drama', '2023-09-05', 'China');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (189, 'scollcutt9', 'Comedy|Crime|Romance', '2023-03-27', 'Portugal');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (127, 'cmaccartera', 'Drama', '2022-12-10', 'Portugal');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (98, 'klantiffb', 'Drama|Sci-Fi', '2023-08-24', 'Sweden');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (90, 'mgergherc', 'Crime|Drama|Thriller', '2022-11-16', 'Bulgaria');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (59, 'dmacgahyd', 'Comedy|Drama', '2023-02-21', 'Western Sahara');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (95, 'nhackwelle', 'Drama', '2022-12-09', 'China');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (175, 'rllewellinf', 'Adventure|Documentary|IMAX', '2022-12-24', 'China');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (72, 'jblumfieldg', 'Action|Adventure|Fantasy|Thriller', '2023-01-24', 'Indonesia');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (110, 'fdammarellh', 'Comedy|Western', '2023-05-03', 'Portugal');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (70, 'lkershowi', 'Comedy|Crime', '2022-12-26', 'Greece');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (118, 'pnutteyj', 'Action|Crime|Drama|Thriller', '2023-01-05', 'Yemen');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (155, 'vheistermannk', 'Action|Adventure|Fantasy|IMAX', '2023-10-20', 'Ukraine');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (48, 'mloguel', 'Action|Adventure|Drama', '2023-03-11', 'Argentina');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (191, 'dstigellm', 'Documentary', '2023-05-09', 'Guatemala');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (87, 'cbatropn', 'Action|Adventure|War', '2023-08-20', 'Ukraine');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (9, 'aabbiso', 'Documentary|Drama', '2023-04-18', 'Belarus');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (127, 'tetiennep', 'Sci-Fi|Thriller', '2023-06-09', 'Peru');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (173, 'ajosskowitzq', 'Comedy', '2023-10-06', 'Philippines');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (86, 'ddooler', 'Comedy', '2023-10-08', 'Vietnam');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (54, 'elatties', 'Drama|Thriller', '2023-05-26', 'Nigeria');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (184, 'challgatht', 'Comedy|Drama', '2022-12-02', 'Norway');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (30, 'ebouttellu', 'Action|Drama|Thriller', '2023-09-02', 'Ukraine');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (141, 'csayesv', 'Documentary', '2023-01-21', 'Mongolia');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (8, 'rcowpew', 'Horror|Thriller', '2023-08-05', 'Indonesia');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (200, 'danstissx', 'Drama', '2023-05-19', 'China');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (2, 'jperringtony', 'Documentary', '2023-05-01', 'China');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (42, 'erylandsz', 'Documentary', '2022-12-01', 'Indonesia');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (192, 'ghargrove10', 'Comedy', '2023-02-02', 'Indonesia');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (142, 'jtodhunter11', 'Action|Children|Sci-Fi|IMAX', '2023-05-24', 'Peru');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (44, 'pbriston12', 'Drama|Thriller|War', '2023-08-06', 'China');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (191, 'plangland13', 'Animation|Horror', '2023-09-30', 'Indonesia');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (122, 'ehanmore14', 'Comedy', '2023-09-19', 'China');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (62, 'kborrott15', 'Musical', '2023-03-12', 'Indonesia');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (105, 'dbonwell16', 'Adventure|Comedy', '2023-03-09', 'Dominican Republic');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (110, 'bwalkowski17', 'Crime|Drama|Horror|Mystery|Thriller', '2023-01-21', 'Malaysia');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (134, 'agribbell18', 'Action|Thriller', '2023-11-08', 'Albania');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (27, 'hverni19', 'Crime|Thriller', '2023-08-20', 'Uruguay');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (190, 'nsewell1a', 'Drama', '2023-09-26', 'Paraguay');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (86, 'lmaycock1b', 'Drama', '2022-12-19', 'Bosnia and Herzegovina');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (69, 'bmargery1c', 'Drama|Romance|War', '2022-11-22', 'China');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (182, 'wgorelli1d', 'Animation|Comedy|Drama', '2023-04-18', 'Indonesia');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (139, 'jfarndell1e', 'Comedy', '2023-09-03', 'Philippines');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (184, 'traffin1f', 'Comedy', '2022-12-16', 'Portugal');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (162, 'jsheaf1g', 'Drama|Musical', '2023-08-18', 'Poland');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (171, 'cbiddell1h', 'Drama', '2023-04-06', 'China');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (91, 'ehannis1i', 'Comedy', '2023-08-05', 'China');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (51, 'dbrandsma1j', 'Horror', '2023-10-16', 'Malta');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (194, 'epainten1k', 'Comedy|Crime|Mystery', '2023-06-18', 'Hungary');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (42, 'bughetti1l', 'Comedy|Horror', '2023-01-13', 'Poland');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (53, 'jbecconsall1m', 'Drama', '2023-02-02', 'Indonesia');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (129, 'charrigan1n', 'Comedy|Crime', '2023-05-30', 'China');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (169, 'jatterbury1o', 'Drama', '2023-02-01', 'Latvia');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (8, 'manersen1p', 'Drama', '2023-03-25', 'Thailand');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (19, 'ohuard1q', 'Drama|Romance', '2023-03-07', 'Venezuela');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (200, 'gdowey1r', 'Drama|Horror|Thriller', '2023-09-04', 'Mauritius');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (129, 'jdillway1s', 'Horror|Romance|Thriller', '2023-06-24', 'Russia');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (168, 'glaugherane1t', 'Comedy', '2023-07-01', 'Indonesia');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (165, 'gbinstead1u', 'Western', '2023-05-22', 'Indonesia');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (43, 'kcanet1v', 'Animation|Horror', '2023-10-18', 'Indonesia');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (50, 'tlumbly1w', 'Comedy|Drama', '2023-04-29', 'Luxembourg');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (94, 'ckeating1x', 'Drama', '2023-04-26', 'Russia');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (128, 'aboutcher1y', 'Comedy|Romance', '2023-04-28', 'Poland');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (66, 'crochford1z', 'Comedy|Drama', '2023-08-07', 'Sweden');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (99, 'dribey20', 'Drama', '2023-01-12', 'Poland');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (60, 'hstollmeyer21', 'Action|Adventure|Drama', '2023-09-24', 'Greece');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (50, 'abalsdone22', 'Action|Crime|Drama', '2023-07-05', 'Greece');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (14, 'afarres23', 'Comedy|Drama|Romance', '2023-09-12', 'Brazil');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (68, 'mshevill24', 'Drama', '2023-02-07', 'Bulgaria');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (152, 'pwhitnell25', 'Comedy', '2023-07-18', 'Nigeria');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (60, 'mshellard26', 'Documentary', '2023-03-07', 'Jamaica');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (83, 'ccradock27', 'Documentary', '2022-12-03', 'France');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (49, 'vcund28', 'Action|Adventure', '2022-11-21', 'Indonesia');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (61, 'cgauntlett29', 'Animation|Children', '2023-05-07', 'Honduras');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (133, 'moxtiby2a', 'Comedy', '2023-05-05', 'Portugal');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (131, 'plarter2b', 'Drama', '2023-01-28', 'Portugal');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (25, 'loregan2c', 'Drama|Romance', '2023-04-15', 'France');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (184, 'varthy2d', 'Drama', '2023-05-28', 'Ukraine');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (121, 'astacey2e', 'Drama', '2023-11-12', 'Libya');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (118, 'aleggis2f', 'Comedy|Drama|Romance', '2022-12-19', 'Indonesia');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (135, 'awillicott2g', 'Adventure|Drama', '2023-05-20', 'China');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (139, 'rreggiani2h', 'Drama', '2023-10-10', 'France');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (117, 'dewbanche2i', 'Documentary', '2023-03-16', 'Indonesia');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (26, 'pspurret2j', 'Comedy|Romance', '2023-10-05', 'Brazil');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (86, 'grexworthy2k', 'Drama|Romance|War', '2023-05-01', 'Cuba');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (137, 'tburrage2l', 'Drama|Horror|Thriller', '2023-08-15', 'Brazil');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (11, 'jlander2m', 'Action|Comedy|Crime', '2023-05-27', 'Greece');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (173, 'slegion2n', 'Horror|Sci-Fi', '2022-11-20', 'Indonesia');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (94, 'jserrier2o', 'Adventure|Comedy', '2023-02-22', 'Russia');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (106, 'bflacknoe2p', 'Drama|Romance', '2023-10-15', 'Sri Lanka');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (53, 'odowning2q', 'Mystery|Thriller', '2023-06-20', 'Germany');
insert into artist (id, nombre, generomusica, nacimiento, paisorigen) values (10, 'dtreneer2r', 'Documentary', '2022-11-25', 'Brazil');

CREATE TABLE album (
    id INT PRIMARY KEY,
    idartista INT,
    nombre VARCHAR(255),
    lanzamiento DATE,
    sellodiscografico VARCHAR(255)
);

insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (137, 1349, 'Not Love, Just Frenzy (Más que amor, frenesí)', '2023-11-09', 'Soup - Campbells Bean Medley');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (33, 1525, 'Shout, The', '2023-01-20', 'Kippers - Smoked');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (95, 1080, 'Tinker Tailor Soldier Spy', '2023-11-14', 'Cheese - Gorgonzola');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (14, 1539, 'Matinée', '2023-07-17', 'Flour - Semolina');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (162, 1537, 'Daughters of the Dust', '2023-08-15', 'Cheese - Parmigiano Reggiano');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (171, 1027, 'Tribulation', '2022-12-26', 'Greens Mustard');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (77, 1349, 'Lentsu', '2023-06-28', 'Chick Peas - Canned');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (131, 1026, 'The Mountain of the Cannibal God', '2023-02-06', 'Soup Campbells - Italian Wedding');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (85, 1013, 'Fired Up', '2023-07-09', 'Radish - Black, Winter, Organic');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (162, 1651, 'Ruling Class, The', '2023-02-08', '7up Diet, 355 Ml');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (181, 1921, 'Wild Boys of the Road', '2023-01-02', 'Food Colouring - Blue');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (191, 1862, 'The Law of the Weakest', '2023-10-22', 'Bread - Crusty Italian Poly');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (67, 1696, 'Sabrina', '2023-02-24', 'Wine - White, French Cross');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (23, 1901, 'Just Another Love Story (Kærlighed på film)', '2023-02-04', 'Mix - Cocktail Strawberry Daiquiri');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (79, 1672, '29 Palms', '2023-01-23', 'Coconut - Whole');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (190, 1381, 'Promise of the Flesh (Yukcheui yaksok)', '2023-05-09', 'Appetizer - Southwestern');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (39, 1186, '21 Grams', '2023-01-30', 'Haggis');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (53, 1194, 'SpaceCamp', '2023-03-29', 'Sugar - Splenda Sweetener');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (123, 1543, 'Save the Last Dance', '2023-06-02', 'Squash - Pepper');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (96, 1102, 'Last Man, The', '2022-12-08', 'Vegetable - Base');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (200, 1198, 'Only Daughter', '2022-12-02', 'Scallops - In Shell');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (181, 1230, 'Good Boy!', '2023-04-05', 'Cheese - Comte');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (169, 1202, 'Disneyland Dream', '2023-01-24', 'Beans - Black Bean, Canned');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (180, 1449, 'Century of the Self, The', '2023-11-05', 'Alize Sunset');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (95, 1196, 'Simon Magus', '2023-06-29', 'Onions - Cippolini');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (2, 1056, 'Under the Sand', '2023-04-16', 'Tray - 16in Rnd Blk');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (136, 1271, 'It''s Such a Beautiful Day', '2023-08-13', 'Relish');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (140, 1598, 'Ring of Terror', '2023-10-13', 'Cumin - Ground');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (148, 1732, 'Traces of Red', '2023-06-05', 'Wine - Barolo Fontanafredda');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (35, 1046, 'Boy in Blue, The', '2023-02-05', 'Juice - Grape, White');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (137, 1972, 'Twist', '2023-05-04', 'Juice - Ocean Spray Kiwi');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (200, 1306, 'Thirteen Days', '2023-06-29', 'Soda Water - Club Soda, 355 Ml');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (108, 1872, 'Negotiator, The', '2023-07-12', 'Cookies - Assorted');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (102, 1136, 'Destroyer', '2023-04-02', 'Lemonade - Black Cherry, 591 Ml');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (78, 1536, 'Love and Honor', '2023-10-18', 'Danishes - Mini Raspberry');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (123, 1254, 'Wrong Man, The', '2023-09-21', 'Puree - Kiwi');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (187, 1286, 'Side Street', '2023-08-30', 'Stock - Beef, Brown');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (15, 1787, 'Stanley and Livingstone', '2023-03-19', 'Capon - Breast, Double, Wing On');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (29, 1197, 'We Bought a Zoo', '2022-11-15', 'Nut - Pistachio, Shelled');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (196, 1448, 'Bloodfist', '2023-09-11', 'Flour - Whole Wheat');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (20, 1953, 'Mirror Has Two Faces, The', '2023-03-08', 'Soup - Knorr, Chicken Noodle');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (139, 1150, 'Ju-on: The Beginning of the End (Ju-on: Owari no hajimari)', '2022-11-20', 'Soup - Base Broth Beef');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (75, 1241, 'Dead Man''s Shoes', '2023-05-20', 'Creme De Menthe Green');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (182, 1769, 'At Berkeley', '2023-11-10', 'Mints - Striped Red');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (138, 1294, 'Our Fathers', '2023-07-24', 'Coffee - Decafenated');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (11, 1060, 'Pursuit of Unhappiness, The (Anleitung zum Unglücklichsein)', '2023-09-25', 'Beef - Chuck, Boneless');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (29, 1112, 'Bungee Jumping of Their Own (Beonjijeompeureul hada)', '2023-10-03', 'Sugar Thermometer');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (30, 1405, 'Flesh Merchant, The (Wild and Wicked, The)', '2023-01-23', 'Lettuce Romaine Chopped');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (143, 1553, 'Abraham''s Valley (Vale Abraão)', '2023-02-03', 'Wine - Barbera Alba Doc 2001');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (114, 1111, 'Dante''s Inferno: An Animated Epic', '2023-10-18', 'Fish - Halibut, Cold Smoked');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (104, 1208, 'Derrida', '2023-04-05', 'Fish - Scallops, Cold Smoked');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (89, 1015, 'Boat That Rocked, The (a.k.a. Pirate Radio)', '2023-01-31', 'Sea Bass - Fillets');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (143, 1634, 'Cold Steel', '2023-09-16', 'Flavouring Vanilla Artificial');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (70, 1952, 'The Halloween That Almost Wasn''t', '2023-05-09', 'Wine - Baron De Rothschild');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (179, 1552, 'Song Is Born, A', '2023-07-05', 'Juice - Pineapple, 341 Ml');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (130, 1437, 'Comedy of Innocence (Comédie de l''innocence)', '2023-04-18', 'Extract - Raspberry');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (46, 1282, 'Eastwood on Eastwood', '2023-10-25', 'Spice - Montreal Steak Spice');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (115, 1831, 'Far from Heaven', '2023-06-19', 'Mussels - Frozen');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (85, 1370, 'Emperor''s New Clothes, The', '2023-09-27', 'Cheese - Parmesan Cubes');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (50, 1124, 'Niagara Motel', '2023-03-04', 'Vector Energy Bar');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (21, 1483, 'Sun Shines Bright, The', '2023-03-29', 'Honey - Comb');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (36, 1486, 'From Dusk Till Dawn 2: Texas Blood Money ', '2023-09-10', 'Jam - Raspberry');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (188, 1954, 'Our Curse', '2023-04-20', 'Soup - Campbells Chili');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (24, 1687, 'Swimsuit Issue, The (Allt flyter)', '2023-07-09', 'Veal - Bones');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (145, 1776, 'Feet First', '2023-09-24', 'Cookie Dough - Double');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (199, 1544, 'Brain Dead', '2023-06-21', 'Tomatoes - Yellow Hot House');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (36, 1712, 'This Island Earth', '2023-07-08', 'Crackers - Water');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (171, 1417, 'Life Is Rosy (a.k.a. Life Is Beautiful) (Vie est belle, La)', '2023-10-24', 'Currants');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (56, 1175, 'The Adventures of André and Wally B.', '2023-03-01', 'Tobasco Sauce');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (145, 1767, 'Sugarland Express, The', '2023-04-27', 'Banana - Leaves');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (160, 1058, '1911 (Xinhai geming)', '2023-07-25', 'Puree - Blackcurrant');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (170, 1097, 'Twilight', '2023-02-16', 'Tahini Paste');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (63, 1823, 'Murderball', '2023-01-11', 'Veal - Shank, Pieces');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (186, 1144, 'Eyes of Laura Mars', '2023-04-29', 'Wine - Red, Cabernet Sauvignon');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (115, 1448, 'That Guy... Who Was in That Thing', '2023-08-10', 'Thyme - Dried');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (165, 1789, 'The Old Maid', '2023-07-18', 'Brownies - Two Bite, Chocolate');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (175, 1442, 'Dead or Alive: Final', '2023-03-09', 'Beans - Green');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (182, 1037, 'Silent Night, Bloody Night', '2023-02-14', 'Rice - Jasmine Sented');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (56, 1567, 'Bodyguards and Assassins', '2023-01-24', 'Banana Turning');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (59, 1316, 'Very British Gangster, A', '2023-10-20', 'Wine - Chateau Bonnet');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (61, 1460, 'Knock on Wood', '2022-11-22', 'The Pop Shoppe - Cream Soda');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (94, 1543, 'Treatment, The', '2023-10-16', 'Bay Leaf Ground');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (80, 1544, 'Un Piede in paradiso', '2023-01-13', 'Crab - Meat');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (13, 1759, 'Son of the Sheik, The', '2023-10-29', 'Napkin - Dinner, White');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (169, 1250, 'Tall Tale', '2023-09-02', 'Appetizer - Asian Shrimp Roll');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (73, 1046, 'Minority Report', '2023-07-17', 'Macaroons - Two Bite Choc');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (26, 1374, 'Broadcast News', '2023-03-03', 'Juice - Propel Sport');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (162, 1077, 'Eye for an Eye', '2023-08-10', 'Pie Pecan');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (38, 1932, 'Wind Will Carry Us, The (Bad ma ra khahad bord)', '2023-08-27', 'Cake - Miini Cheesecake Cherry');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (93, 1808, 'Charlie Chan in Rio', '2023-01-22', 'Bread - Multigrain Oval');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (87, 1603, 'Bolero', '2023-05-20', 'Tart Shells - Savory, 3');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (31, 1073, 'Maria, ihm schmeckt''s nicht! (Maria, He Doesn''t Like It)', '2022-12-01', 'Tart Shells - Sweet, 3');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (62, 1041, 'Redes (Fishermen''s Nets) (Wave, The)', '2023-10-10', 'Flour - Rye');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (196, 1034, 'How to Train Your Dragon 2', '2023-07-05', 'Mushroom - Morel Frozen');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (141, 1526, 'Raisin in the Sun, A', '2023-03-27', 'Juice - Apple 284ml');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (22, 1275, 'Persona', '2023-07-31', 'Corn - Cream, Canned');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (26, 1980, 'Den, The', '2022-11-20', 'Juice - Apple 284ml');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (41, 1400, 'Atragon (Kaitei Gunkan)', '2023-10-24', 'Coffee - Irish Cream');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (1, 1805, 'Anatomy of a Murder', '2023-10-17', 'Sauce Tomato Pouch');
insert into album (id, idartista, nombre, lanzamiento, sellodiscografico) values (137, 1088, 'Wedding March, The', '2023-08-18', 'Sambuca - Opal Nera');